version: "3"
services:
  web:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - nginx:/etc/nginx/conf.d
    labels:
      ecs-local.task-definition-input.type: remote-wordpress-nginx
      ecs-local.task-definition-input.value: docfox-wordpress-nginx
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/docfox-wordpress
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
  docfox-wordpress:
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}
      MY_KEY: ${MY_KEY}
      WP_DEBUG: ${WP_DEBUG}
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: 338196870821.dkr.ecr.us-east-1.amazonaws.com/wordpress-demo:wordpress-bff59ba629fa4b3cf92efe19b6e67ceb27aa32d7
    labels:
      ecs-local.task-definition-input.type: remote
      ecs-local.task-definition-input.value: docfox-wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/docfox-wordpress
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
    volumes:
      - wordpress:/var/www/html
      - nginx:/nginx
networks:
  ecs-local-network:
    external: true
volumes:
  wordpress:
  nginx:
