name: Deploy to Amazon Container Registry

on: [push]

jobs:
  deploy:
    name: Deploy
    if: "!contains(github.event.head_commit.message, 'ecr deploy')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WORDPRESS_REPO: nziswano-wordpress
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_TAG_LATEST: latest
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$WORDPRESS_REPO:$IMAGE_TAG -t $ECR_REGISTRY/$WORDPRESS_REPO:$IMAGE_TAG_LATEST .
        docker push $ECR_REGISTRY/$WORDPRESS_REPO:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
