name: Test and deploy my CDK configuration for Wordpress
on: 
  push:
    branches:
      - 'feature/**'
    paths:
      - 'lib/**'
      - 'test/**'
      - 'bin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        
      - name: actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm install

      - name: CDK Synth
        uses: arnaskro/aws-cdk-v2-github-actions@v2.2.0
        with:
          cdk_subcommand: 'synth'
      - name: CDK Test
        run: npm run test
